RULES     = RULE ( _ RULE | ( _ OR _ !NOT RULE))*
<RULE> 	  = NOT? (OPERATOR | KEYWORD | QUOTED |  '(' RULES ')' )

QUOTED    = '"' (NOT? KEYWORD _ )+ '"' ('~' numbers)?
KEYWORD   = #'[#@]'? word (word | spec_word)*

OPERATOR  = op (':' word)?

<spec_word> = #"[!%&\*+-.'/;<=>?,#@]+" 
<word>      = !OR #"[a-zA-Z0-9_]+" 

NOT	  = '-'
OR	  = #'\bOR\b' 

numbers   = #"[0-9]+"
<_>       = <#"\s*">

<op>	  = ('contains' | 'from' | 'url_contains' | 'has:links' | 'lang' | 'has:lang' | 'sample')+
stopwords = ('a' | 'an' | 'and' | 'at' | 'but' | 'by' | 'com' | 'from' | 'http' | 'https' | 'if' | 'in' | 'is' | 'it' | 'its' | 'me' | 'my' | 'or' | 'rt' | 'the' | 'this' | 'to' | 'too' | 'via' | 'we' | 'www' | 'you')+
