RULES     = RULE (<blank*> RULE | (<blank*> OR <blank*> !'-' RULE))*
RULE 	  = '-'? (OPERATOR | KEYWORD | QUOTED |  '(' RULES ')' )

QUOTED    = '"' ('-'? KEYWORD <blank*>)+ '"' ('~' number)?
<KEYWORD> = #'[#@]'? word (word | spec_word)*

OPERATOR  = OP (':' word)?

spec_word = #"[!%&\*+-.'/;<=>?,#@]+" 
word	  = !OR #"[a-zA-Z0-9_]+" 

OR	  = #'\bOR\b' 

number    = #"[0-9]+"
blank     = #'\s'

<OP>	  = ('contains' | 'from' | 'url_contains' | 'has:links' | 'lang' | 'has:lang' | 'sample')+
STOPWORDS = ('a' | 'an' | 'and' | 'at' | 'but' | 'by' | 'com' | 'from' | 'http' | 'https' | 'if' | 'in' | 'is' | 'it' | 'its' | 'me' | 'my' | 'or' | 'rt' | 'the' | 'this' | 'to' | 'too' | 'via' | 'we' | 'www' | 'you')+
